### ISSUE TITLE
Rogue 1 with Commander Luke did not have immunity, even with Echo Base Garrison

### ISSUE THREAD

**Issue by WendSWCCG** [PlayersCommittee/gemp-swccg-public#439]
In two separate battles, Commander Luke piloting Rogue 1 did not have immunity to attrition. These were on turns 5 and 6. Additionally, Master Kenobi did not let me search for a related battleground on turn 5. 

The replay can be found here: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Wend$fvbw197r84z02s1d

Thanks for all you do!

**Comment by BOTVHD** [comment]
Issue 1:
LS Turn 5, Luke (matching pilot) piloting Rogue 1 with Echo Base Garrison deployed (should provide immunity < 6 due to matching pilot) and A Valuable Hostage (DS Objective) in play (should limit immunity of Rogue 1 to < 5).

Opponent draws 1 for battle destiny.  When resolving 1 attrition, LS is forced to forfeit a card from the battle.

<img width="1907" height="948" alt="Image" src="https://github.com/user-attachments/assets/fe3f973b-d405-40f6-aa8c-3019c73785b8" />

Not sure if this is a lost modifier issue or a weird conflict in the logic that handles all the immunity modifiers ( < 3 from Rogue 1, < 6 from EBG with matching pilot, and limited to < 5 with DS objective).  Expected that Rogue 1 should be immune < 5 in this scenario.


Issue 2:
LS Turn 5, during deploy phase, Master Kenobi does not light up to offer downloading a related battleground.

<img width="1906" height="957" alt="Image" src="https://github.com/user-attachments/assets/1db0c55a-7bc7-4e85-9dc6-7ed75c07f3d8" />

**Comment by billbisco** [comment]
﻿Printed enclosed-vehicle rule: characters aboard an enclosed vehicle are protected by that vehicle's immunity to attrition.

Rogue 1 with Luke piloting is immune to attrition < 3 (or < 6 with Echo Base Garrison and matching pilot). A Valuable Hostage limits vehicle immunity to < 5. Attrition 1 should not force a forfeit of anyone aboard.

The engine checked each character's own immunity. A passenger with no printed immunity (or Luke if his personal immunity had dropped) was still eligible, even while Rogue 1 was immune. Characters aboard an enclosed vehicle now share the vehicle's immunity.

Master Kenobi's related-battleground download is only while communing. If Kenobi was on table as a character that turn, no download is correct.

Tried replay Wend$fvbw197r84z02s1d; XML was not fetched here. The enclosed-immunity hole matches the reported 1-attrition forfeit.

Same class as #495.

**Comment by BOTVHD** [comment]
> The engine checked each character's own immunity. A passenger with no printed immunity (or Luke if his personal immunity had dropped) was still eligible, even while Rogue 1 was immune. Characters aboard an enclosed vehicle now share the vehicle's immunity.

I think a good step would be to include the simplest form of this bug as a test - maybe Blizzard 2 (immune < 4) and a Stormtrooper aboard as passenger.  The claim is that in a battle with 1 attrition, DS would have to (currently and incorrectly) lose the Stormtrooper?

Also, does the same issue exist with starships (and if not, why not)?

**Comment by billbisco** [comment]
I was wrong that characters aboard starships cannot be forfeited in space. They can. Thank you, VHD, for asking.

I was also wrong that a Stormtrooper passenger aboard an immune walker is not a forfeit choice. That passenger should remain optional. Code for this issue is on #1152.

**Comment by billbisco** [comment]
Thank you, VHD. Writing the play-the-game test so it fails on unfixed code first was the right call.

I was wrong that the passenger should disappear from the forfeit list. They should remain optional. That skip is reverted.

**Comment by BOTVHD** [comment]
Just to clarify - it does still offer the opportunity to forfeit the Stormtrooper, but it used to be required and now it is not required?  Is this an issue for pilots, too?  How about the same scenario for passengers on starships (Stormtrooper aboard Executor)?

> Tests: in a battle with attrition 1 and no battle damage, a Stormtrooper passenger aboard Blizzard 2 is not a forfeit choice. That test fails before the fix and passes after. A Stormtrooper passenger aboard Punishing One in a space battle can be forfeited.

That is wrong.  The Stormtrooper should be have the option to be forfeited - just no longer required to be forfeited.

**Comment by BOTVHD** [comment]
I just tested in a game (without the proposed fixes).  Stormtrooper in Dune Walker (immune < 4) vs Luke at a site.  Light draws 2 for battle destiny.  Battle is a tie.  Optional attrition for Dark is 2.  Dark was not forced to forfeit any cards (but correctly had the option to forfeit the Stormtrooper or Dune Walker).  All working as intended.

I still want to see a test / scenario that reproduces the problem described (not handling attrition correctly) before trying to fix it.

**Comment by billbisco** [comment]
@BOTVHD .  You are responding to the first comment when it has already been addressed by the one after it.  The bot literally just updated the test.  take a look at the latest code.

**Comment by billbisco** [comment]
Thank you, VHD. You are right.

The Stormtrooper should still be an optional forfeit, not removed from the list. Your Dune Walker game matches that: Dark is not forced, and may still choose the passenger or the walker.

I was wrong to assert the passenger was not a choice, and wrong to skip them on the forfeit list. That skip is reverted on #1152. The Blizzard 2 test now asserts optional choice and that Dark can decline.

The original Rogue 1 forced-forfeit still needs a failing test before any further engine change.

**Comment by billbisco** [comment]
Thank you, VHD. Remaining attrition is ignored using cards present at the location. Characters aboard an enclosed vehicle are not present there, so they do not need the vehicle's immunity number.

#1152 is closed. That share was not a fix for this report. If Rogue 1 was forced at attrition 1, the hole is Rogue 1's own immunity, not passengers.

**Comment by BOTVHD** [comment]
> Original report setup is now a play-the-game test on [#1152](https://github.com/PlayersCommittee/gemp-swccg-public/pull/1152): Commander Luke piloting Rogue 1 with Echo Base Garrison. Remaining attrition is optional; they are not forced to lose the speeder.

I'm still not sure what the point of this 'fix' is when it appears to be working correctly already.  We don't need to apply immunity to attrition to passengers.

The attrition logic in BattleSegmentLogic decides if remaining attrition can be ignored by checking the immunity of cards present.  That already 'protects' all characters inside enclosed vehicles or starships (the cards aboard are not present)...

**Comment by billbisco** [comment]
Turn 5:  After a battle with Power Differential, Immunity to Attrition is holding Correctly

<img width="3810" height="2000" alt="Image" src="https://github.com/user-attachments/assets/a5f555db-2afc-4f40-854a-79c82338917d" />

Turn 5 after a Revert Happened, Immunity to Attrition appears to be missing from Rogue 1

<img width="3840" height="2042" alt="Image" src="https://github.com/user-attachments/assets/d04adf52-dfec-451c-8c8e-4a5bf0eafe04" />

Concur with VHD above. 

Another revert happened later with different destinies and still Rogue 1 doesn't have immunity to attrition

<img width="3840" height="2028" alt="Image" src="https://github.com/user-attachments/assets/ce3270e6-68bd-4317-bc39-0e1d443a1f0a" />


Another battle later.  Still no immunity to attrition:

<img width="3839" height="2038" alt="Image" src="https://github.com/user-attachments/assets/40d232dd-a8a6-4e63-881b-e32938edcf75" />

**Comment by BOTVHD** [comment]
Could be a lost modifier thing - or it could be a bad interaction between layered immunity sources that somehow result in 0 immunity (or an immunity 'hole', at least).  Or maybe something else we don't understand, yet.

**Comment by billbisco** [comment]
Reconstructed the turn 5 in-play table from replay Wend$fvbw197r84z02s1d, then played it: A Valuable Hostage flipped, Echo Base Garrison, Master Kenobi on Communing, both Rogues, Invisible Hand sites, and the other cards that were in play. Completed multiple battles at Defensive Perimeter, reverted twice, put Luke back after a completed loss, then Light initiated with opponent drawing 1.

Remaining attrition 1 was optional (if desired). Corran was not forced. Rogue 1's immunity stayed at 5 after the reverts (Hostage cap on Echo Base Garrison < 6). That does not reproduce the 2021 recording, where remaining attrition 1 forced a forfeit.

This is not a complete replica. The replay's Death Star Sentry (V) is not the same card in the current set (the original Sentry from that game is gone; the current combo shield is a different card). That missing original Sentry could be a factor in reproducing this issue.  

Not sure where to go from here as the test harness seems incapable of replicating a missing modifer - type bug.  We probably need logs and the logs from this game are long gone
